var footer = document.querySelector("footer");
//console.log(footer);
footer.style.backgroundColor = "#d7ddf3";
var tagline = document.querySelector(".tagline");
//console.log(tagline);
tagline.innerText = "Where roses really smell like poo poo poo";
var address = document.querySelector("address");
//console.log(address);
address.style.lineHeight = "1.5em";
address.style.fontSize = "1.75em";
var everyDay = document.querySelector(".contact h3");
//console.log(everyDay);
everyDay.innerHTML = "We're here for you <em>every day</em> of the week.";
var instagram = document.querySelector(".fa-instagram");
//console.log(instagram);
instagram.style.color = "#d45bb9";
var facebook = document.querySelector(".fa-facebook");
//console.log(facebook);
facebook.style.color = "#6a99b5";
var openingHours = document.querySelector("footer p");
//console.log(openingHours);
openingHours.style.border = "1px solid #d45bb9";
openingHours.style.padding = "1em";
